module.exports = {
  apps: [
    {
      name: 'optiohire-backend',
      script: './backend/dist/server.js',
      cwd: '/home/optiohire/optiohire',
      instances: 1,
      exec_mode: 'fork',
      env_file: '/home/optiohire/optiohire/backend/.env',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
        DATABASE_URL: 'postgresql://postgres.qijibjotmwbikzwtkcut:HireBit%40254%23.%24@aws-0-us-east-1.pooler.supabase.com:6543/postgres',
        DB_SSL: 'true',
        JWT_SECRET: '38970ddabcd7f6a37d4176d9c3f2e06571a48ccf173a13d8a070e5e207ac2e96b8e5d569e95fb29a4bfe9527b689387525eda70219e38411a8e069e27eef6942',
        GEMINI_API_KEY: 'AIzaSyAVB1-3g8umuSxaLD5STEqpWV5No5LEl_o',
        SMTP_HOST: 'smtp.gmail.com',
        SMTP_PORT: '587',
        SMTP_USER: 'hirebitapplications@gmail.com',
      },
      error_file: '/home/optiohire/logs/backend-error.log',
      out_file: '/home/optiohire/logs/backend-out.log',
      log_file: '/home/optiohire/logs/backend-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '500M',
    },
    {
      name: 'optiohire-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/home/optiohire/optiohire/frontend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      error_file: '/home/optiohire/logs/frontend-error.log',
      out_file: '/home/optiohire/logs/frontend-out.log',
      log_file: '/home/optiohire/logs/frontend-combined.log',
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '800M',
    },
  ],
}

